from __future__ import annotations

from eas.context.paths import WorkspacePaths

DRAFT_TEMPLATE = """# Architecture (draft)

> Generated by `engineering-agent analyze --write-draft`. Complete this document by running the **architect** agent in your IDE — see `.ai/hosts/prompts.md`.

Requirement: `.ai/workspace/requirement.md`

## Summary

(TODO — run architect agent)

## Open questions

- (TODO)
"""


def write_minimal_draft(paths: WorkspacePaths) -> str:
    """Write a minimal architecture stub if missing. Returns draft status label."""
    if paths.architecture_md.is_file():
        return "skipped (exists)"

    paths.architecture_md.parent.mkdir(parents=True, exist_ok=True)
    paths.architecture_md.write_text(DRAFT_TEMPLATE, encoding="utf-8")
    return "created"
